apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      imagePullSecrets:
      - name: azure-registry-secret
      containers:
      - name: wisecow
        image: mycontainerregistrywc.azurecr.io/wisecow:latest
        ports:
        - containerPort: 80
