name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.roshan98 }}
          password: ${{ secrets.KAvi980217## }}

      - name: Build Docker image
        run: docker build -t wisecow:latest .

      - name: Push Docker image
        run: |
          docker tag wisecow:latest roshan98/wisecow:latest
          docker push roshan98/wisecow:latest