name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.mycontainerregistrywc.azurecr.io }}
          username: ${{ secrets.myContainerRegistrywc }}
          password: ${{ secrets.KI9PkS7U+Q65YQZyj05jDM/X9faulT3WRlHPRM1sXZ+ACRC8wZMH }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.mycontainerregistrywc.azurecr.io }}/wisecow-image .

      - name: Push Docker image to Azure Container Registry
        run: docker push ${{ secrets.mycontainerregistrywc.azurecr.io }}/wisecow-image
